version: '3'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/app/.env
    links:
      - "db:db"

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5434:5432"
    env_file:
      - ./backend/app/.env

  bot:
    build:
      context: ./telegram_bot
      dockerfile: Dockerfile
    depends_on:
      - app
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
